[colors]
ansi = [
    "#161215",
    "#ffb4ab",
    "#f5b8a7",
    "#dabfd2",
    "#ffabf3",
    "#f5b8a7",
    "#dabfd2",
    "#e9e0e4",
]
background = "#161215"
brights = [
    "#9a8d95",
    "#ffb4ab",
    "#f5b8a7",
    "#dabfd2",
    "#ffabf3",
    "#f5b8a7",
    "#dabfd2",
    "#e9e0e4",
]
cursor_bg = "#e9e0e4"
cursor_border = "#e9e0e4"
cursor_fg = "#161215"
foreground = "#e9e0e4"
selection_bg = "#4e444b"
selection_fg = "#d1c2cb"

[metadata]
name = "Noctalia"
